# dbt profile for Dune API connection
balancer:
  target: dev
  outputs:
    dev:
      type: trino
      method: jwt
      user: "{{ env_var('DUNE_TEAM_NAME') }}"
      jwt_token: "{{ env_var('DUNE_API_KEY') }}"
      host: trino.api.dune.com
      port: 443
      database: dune
      schema: "{{ env_var('DUNE_TEAM_NAME') }}__tmp_{{ env_var('DEV_SCHEMA_SUFFIX', '') }}"
      threads: 4
      http_timeout: 120
      http_scheme: https
      cert: true
      session_properties:
        transformations: true
      timezone: UTC
    prod:
      type: trino
      method: jwt
      user: "{{ env_var('DUNE_TEAM_NAME') }}"
      jwt_token: "{{ env_var('DUNE_API_KEY') }}"
      host: trino.api.dune.com
      port: 443
      database: dune
      schema: "{{ env_var('DUNE_TEAM_NAME') }}"
      threads: 4
      http_timeout: 120
      http_scheme: https
      cert: true
      session_properties:
        transformations: true
      timezone: UTC
